services:
  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma_db_container:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: always

  backend:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docs:/usr/share/nginx/html:ro
      - ./data:/usr/share/nginx/data:ro
    depends_on:
      - backend
    restart: always

  nginx-subdomain:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/private.key:/etc/ssl/private/_.digitalalchemisten.de_private_key.key:ro
      - ./ssl/_.digitalalchemisten.de_bundle.crt:/etc/ssl/certs/_.digitalalchemisten.de_bundle.crt:ro
    depends_on:
      - backend
    restart: always
